// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Infrastructure.Database;

#nullable disable

namespace SmartHome.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Domain.Entities.Appliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalibratedHoursPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CalibrationFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursPerDay")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ShellyDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WattMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WattMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WattTypical")
                        .HasPrecision(8, 1)
                        .HasColumnType("decimal(8,1)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.BillingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalibrationFactor")
                        .HasPrecision(6, 4)
                        .HasColumnType("decimal(6,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DayAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExplainedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExplainedPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FromReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NightAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NightConsumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TariffSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ToReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalConsumption")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromReadingId");

                    b.HasIndex("ToReadingId");

                    b.HasIndex("UserId");

                    b.ToTable("BillingPeriods");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DayReading")
                        .HasPrecision(10, 1)
                        .HasColumnType("decimal(10,1)");

                    b.Property<string>("InputMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTwoZone")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NightReading")
                        .HasPrecision(10, 1)
                        .HasColumnType("decimal(10,1)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.TariffSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DayRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("decimal(6,4)");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("bit");

                    b.Property<decimal>("NightRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SingleRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("decimal(6,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TariffSettings");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.Appliance", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.User", "User")
                        .WithMany("Appliances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.BillingPeriod", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.MeterReading", "FromReading")
                        .WithMany("BillingPeriodsFrom")
                        .HasForeignKey("FromReadingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartHome.Domain.Entities.MeterReading", "ToReading")
                        .WithMany("BillingPeriodsTo")
                        .HasForeignKey("ToReadingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartHome.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromReading");

                    b.Navigation("ToReading");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.MeterReading", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.User", "User")
                        .WithMany("MeterReadings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.TariffSettings", b =>
                {
                    b.HasOne("SmartHome.Domain.Entities.User", "User")
                        .WithOne("TariffSettings")
                        .HasForeignKey("SmartHome.Domain.Entities.TariffSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.MeterReading", b =>
                {
                    b.Navigation("BillingPeriodsFrom");

                    b.Navigation("BillingPeriodsTo");
                });

            modelBuilder.Entity("SmartHome.Domain.Entities.User", b =>
                {
                    b.Navigation("Appliances");

                    b.Navigation("MeterReadings");

                    b.Navigation("TariffSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
